name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Replace variables
      env:
        TOKEN: ${{ vars.TOKEN_PLACEHOLDER }}
        GIST: ${{ vars.GIST_ID }}
      run: |
        sed -i "s/\${{ vars.TOKEN_PLACEHOLDER }}/$TOKEN/g" animateur.html
        sed -i "s/\${{ vars.GIST_ID }}/$GIST/g" animateur.html
        
    - name: Setup Pages
      uses: actions/configure-pages@v3
      
    - name: Upload
      uses: actions/upload-pages-artifact@v2
      with:
        path: '.'
        
    - name: Deploy
      uses: actions/deploy-pages@v2